set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES arm64)
# UE5.8.1 Engine/Config/Mac/Mac_SDK.json: game and Program targets use macOS 14.
set(VCPKG_OSX_DEPLOYMENT_TARGET 14.0)
