# The Unreal v26 compiler, libc++ and fixed sysroot must also build vcpkg ports.
if(NOT DEFINED ENV{CANOPY_LINUX_TOOLCHAIN_ROOT} OR NOT DEFINED ENV{CANOPY_LINUX_SYSROOT}
   OR NOT DEFINED ENV{CANOPY_LINUX_LIBCXX_INCLUDE} OR NOT DEFINED ENV{CANOPY_LINUX_LIBCXX_LIBDIR})
    message(FATAL_ERROR "The v26 triplet requires compiler, sysroot, libc++ headers and library paths")
endif()
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/v26-chainload.cmake")
set(VCPKG_ENV_PASSTHROUGH CANOPY_LINUX_TOOLCHAIN_ROOT CANOPY_LINUX_SYSROOT
    CANOPY_LINUX_LIBCXX_INCLUDE CANOPY_LINUX_LIBCXX_LIBDIR)
